#include <stdafx.hpp>
#include <string>

#include <render/menu/localization.hpp>

namespace render::localization
{

namespace
{

std::atomic<id> g_current{id::en};

const std::unordered_map<std::string_view, const char *> &russian()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // --- navigation -------------------------------------------------
        {"Aimbot", "Аим"},
        {"Triggerbot", "Триггер"},
        {"Visuals", "Визуалы"},
        {"Misc", "Разное"},

        // --- weapon group tabs ------------------------------------------
        {"Global", "Общие"},
        {"Pistol", "Пистолеты"},
        {"SMG", "ПП"},
        {"Rifle", "Винтовки"},
        {"Shotgun", "Дробовики"},
        {"Sniper", "Снайперки"},
        {"Heavy", "Пулемёты"},

        // --- combat cards -----------------------------------------------
        {"TARGETING", "НАВЕДЕНИЕ"},
        {"PENETRATION", "ПРОБИТИЕ"},
        {"VISUALIZATION", "ОТОБРАЖЕНИЕ"},
        {"TRIGGERBOT CORE", "ТРИГГЕР"},
        {"ADVANCED MODE", "РАСШИРЕННЫЙ"},
        // This card holds Auto Stop / Early Auto Stop -- it is about stopping
        // before the shot, not about the movement features in Misc.
        {"MOVEMENT", "АВТОСТОП"},
        {"OVERRIDE SETTINGS", "ПЕРЕОПРЕДЕЛЕНИЕ"},

        // --- combat rows ------------------------------------------------
        {"Master Switch", "Включить"},
        {"Activation", "Активация"},
        {"Activation Mode", "Режим активации"},
        {"Hold", "По удержанию"},
        {"Always On", "Всегда"},
        {"Toggle", "Переключение"},
        {"Damage Override", "Переопределение урона"},
        {"Override Damage", "Альтернативный урон"},
        {"Checks", "Условия"},
        {"Jump", "Прыжок"},
        {"Flash", "Ослепление"},
        {"Airborne", "В воздухе"},
        {"Flashed", "Ослепление"},
        {"Threshold", "Порог"},
        {"Smoke", "Дым"},
        {"Walls", "Стены"},
        {"Block", "Запрет"},
        {"Penetration", "Пробитие"},
        {"Ignore", "Игнорировать"},
        {"Trigger Key", "Бинд"},
        {"FOV", "FOV"},
        {"FOV Profile", "Профиль FOV"},
        {"Radius", "Радиус"},
        {"Max Radius", "Макс. радиус"},
        {"Min Radius", "Мин. радиус"},
        {"Full Size At", "Полный размер до"},
        {"Min Size At", "Мин. размер после"},
        {"Advanced", "Дополнительно"},
        {"Fixed", "Фиксированный"},
        {"Distance", "По дистанции"},
        {"Target", "На цели"},
        {"Near Distance", "Ближняя дистанция"},
        {"Near FOV", "Ближний FOV"},
        {"Far Distance", "Дальняя дистанция"},
        {"Far FOV", "Дальний FOV"},
        {"Acquisition Area", "Область захвата"},
        {"Target Point", "Точка наведения"},
        {"Show FOV", "Показывать FOV"},
        {"Visualization", "Визуализация"},
        {"Smoothing", "Сглаживание"},
        {"Humanize", "Хуманизация"},
        {"Humanizer Tuning", "Тонкая настройка"},
        {"Humanizer Profile", "Профиль хуманизации"},
        {"Motion", "Движение"},
        {"Behavior", "Поведение"},
        {"Gravity", "Притяжение"},
        {"Wind", "Отклонение"},
        {"Max Step", "Максимальный шаг"},
        {"Damping", "Затухание"},
        {"Reaction Min", "Мин. реакция"},
        {"Reaction Max", "Макс. реакция"},
        {"Curve", "Кривизна"},
        {"Overshoot Chance", "Шанс перелёта"},
        {"Overshoot Amount", "Сила перелёта"},
        {"Jitter", "Микродрожание"},
        {"Deadzone", "Мёртвая зона"},
        {"Hitboxes", "Хитбоксы"},
        {"Multi-Point", "Мультипоинт"},
        {"Cap Points", "Торцевые точки"},
        {"Side Points", "Боковые точки"},
        {"Head Scale", "Масштаб головы"},
        {"Body Scale", "Масштаб тела"},
        {"Limbs Scale", "Масштаб конечностей"},
        {"Prediction", "Предикт"},
        {"Max Horizon", "Горизонт предикта"},
        {"Acceleration", "Учитывать ускорение"},
        {"RCS", "Контроль отдачи"},
        {"Start Bullet", "Начальная пуля"},
        {"Pitch Strength", "Сила по вертикали"},
        {"Yaw Strength", "Сила по горизонтали"},
        {"Humanization", "Хуманизация"},
        {"Response", "Отклик"},
        {"Gain Randomness", "Разброс силы"},
        {"Drift", "Дрейф"},
        {"Correction Time", "Время коррекции"},
        {"Smoothness", "Плавность"},
        {"Strength Variation", "Вариация силы"},
        {"Path Drift", "Дрейф траектории"},
        {"Wall Policy", "Прострелы"},
        {"Only Visible", "Только видимые"},
        {"Shot Timing", "Тайминг выстрела"},
        {"Randomize", "Рандомизация"},
        {"Outlier Chance", "Шанс выброса"},
        {"Outlier Delay", "Задержка выброса"},
        {"Lethal Only", "Только смертельный урон"},
        {"R8 Readiness", "Готовность R8"},
        {"Release Margin", "Запас отпускания"},
        {"Key", "Бинд"},
        {"Visible Only", "Только по видимым"},
        {"Predictive", "Предикт"},
        {"Recoil Sync", "Контроль отдачи"},
        {"Auto Wall", "Autowall"},
        {"Extreme Wall", "Экстремальный прострел"},
        {"Min Damage", "Мин. урон"},
        {"Draw FOV Circle", "Рисовать FOV"},
        {"Mode", "Режим"},
        {"Interface Colors", "Цвета интерфейса"},
        {"Typography", "Текст"},
        {"Primary Text", "Основной текст"},
        {"Muted Text", "Вторичный текст"},
        {"Surfaces", "Поверхности"},
        {"Menu Background", "Фон меню"},
        {"Controls", "Элементы управления"},
        {"Containers", "Контейнеры"},
        {"Popups", "Всплывающие окна"},
        {"Interaction", "Взаимодействие"},
        {"Accent", "Акцент"},
        {"Hover", "Наведение"},
        {"Borders", "Границы"},
        {"Seed Type", "Сид"},
        {"Hitchance", "Шанс попасть"},
        {"Delay (ms)", "Задержка (мс)"},
        {"Reaction Time (ms)", "Время реакции (мс)"},
        {"Auto Stop", "Auto Stop"},
        {"Early Auto Stop", "Early Auto Stop"},
        {"Delay Before", "Задержка до"},
        {"Delay After", "Задержка после"},
        {"Randomize (+-)", "Рандом (±)"},
        {"Inherit Global Settings", "Как в общих"},

        // --- shared option values ---------------------------------------
        {"Advanced", "Расширенный"},
        {"None", "Нет"},
        {"All", "Все"},
        {"Restricted", "Ограниченный"},
        {"Unrestricted", "Свободный"},
        {"Head", "Голова"},
        {"Body", "Тело"},
        {"Arms", "Руки"},
        {"Legs", "Ноги"},

        // --- visuals tabs -----------------------------------------------
        {"Players", "Игроки"},
        {"Items", "Дроп"},
        {"Projectiles", "Гранаты"},
        {"Bomb", "Бомба"},
        {"Radar", "Радар"},
        {"World", "Мир"},
        {"Crosshair", "Прицел"},

        // --- expanded radar / crosshair ---------------------------------
        {"Player Names", "Имена игроков"},
        {"Player Health", "Здоровье игроков"},
        {"Player Armor", "Броня игроков"},
        {"Player Weapon", "Оружие игроков"},
        {"Grenade Markers", "Маркеры гранат"},
        {"Grenade Trajectories", "Траектории гранат"},
        {"Grenade Zones", "Зоны гранат"},
        {"Information Scale", "Масштаб информации"},
        {"Overlay Enemy Markers", "Маркеры противников"},
        {"Enemy Marker", "Маркер противника"},
        {"View Direction", "Направление взгляда"},
        {"Status Text", "Текст состояния"},
        {"Marker Scale", "Масштаб маркера"},
        {"Text Outline", "Обводка текста"},
        {"HE Color", "Цвет HE"},
        {"Flash Color", "Цвет световой"},
        {"Smoke Color", "Цвет дыма"},
        {"Molotov Color", "Цвет огня"},
        {"Decoy Color", "Цвет ложной"},
        {"Line Thickness", "Толщина линии"},
        {"End Point Size", "Размер конечной точки"},
        {"Fill Opacity", "Прозрачность заливки"},
        {"Outline Opacity", "Прозрачность контура"},
        {"In-Game Avatars", "Внутриигровые аватары"},
        {"Outline Color", "Цвет обводки"},
        {"Outline Thickness", "Толщина обводки"},

        // --- player esp -------------------------------------------------
        {"MASTER", "ОСНОВНОЕ"},
        {"BOUNDING BOX", "БОКС"},
        {"DETAILS", "ИНФА"},
        {"SKELETON & HITBOXES", "СКЕЛЕТ И ХИТБОКСЫ"},
        {"Enable Player ESP", "Включить ESP"},
        {"Legit Sync", "Легитная синхронизация"},
        {"Spectator Sync", "Синхронизация со зрителями"},
        {"Direct Visibility", "Прямая видимость"},
        {"Radar Spotted", "Обнаружение радаром"},
        {"Audible Sounds", "Слышимые звуки"},
        {"Radar Hold", "Время радара"},
        {"Sound Hold", "Время звука"},
        {"Hearing Distance", "Дистанция слышимости"},
        {"Pulse Minimum", "Минимум пульсации"},
        {"Pulse Maximum", "Максимум пульсации"},
        {"Pulse Period", "Период пульсации"},
        {"Show Box", "Бокс"},
        {"Style", "Стиль"},
        {"Full", "Полный"},
        {"Cornered", "Углы"},
        {"Corner Length", "Длина углов"},
        {"Background Fill", "Заливка"},
        {"Box Visible Color", "Бокс: видимые"},
        {"Box Occluded Color", "Бокс: за стеной"},
        {"Fill Visible Color", "Заливка: видимые"},
        {"Fill Occluded Color", "Заливка: за стеной"},
        {"Show Name", "Ник"},
        {"Show Weapon", "Оружие"},
        {"Ammo Indicator", "Индикатор патронов"},
        {"Exact Ammo Count", "Точное число патронов"},
        {"Empty Color", "Цвет пустой части"},
        {"Bomb Damage", "Урон от бомбы"},
        {"Health Bar", "Бар ХП"},
        {"Ammo Bar", "Бар патронов"},
        {"Info Flags", "Флаги"},
        {"Chams", "Чамсы"},
        {"Antialiasing", "Сглаживание"},
        {"Model Glow", "Свечение модели"},
        {"Glow Color", "Цвет свечения"},
        {"Glow Radius", "Радиус свечения"},
        {"Glow Strength", "Яркость свечения"},
        {"Glow Layers", "Слои свечения"},
        {"Death Shatter", "Распад при смерти"},
        {"On Hit Chams", "Чамсы при попадании"},
        {"Kill Particles", "Частицы смерти"},
        {"Particle Color", "Цвет частиц"},
        {"Particle Duration", "Время частиц"},
        {"Particle Size", "Размер частиц"},
        {"Particle Count", "Количество частиц"},
        {"On Shot Chams", "Чамсы при выстреле"},
        {"Ghost Duration", "Время слепка"},
        {"Ghost Appearance", "Вид слепка"},
        {"Occlusion", "Перекрытия"},
        {"Dynamic Doors", "Динамические двери"},
        {"Smoke Occlusion", "Перекрытие дымом"},
        {"Chams Visible", "Чамсы: видимые"},
        {"Chams Occluded", "Чамсы: за стеной"},
        {"Show Skeleton", "Скелет"},
        {"Show Head Circle", "Круг на голове"},
        {"Show View Line", "Линия взгляда"},
        {"Offscreen Arrows", "Стрелки за экраном"},
        {"Arrow Color", "Цвет стрелки"},
        {"Arrow Size", "Размер стрелки"},
        {"Arrow Radius", "Радиус стрелок"},
        {"Bloom Speed", "Скорость свечения"},
        {"Minimum Glow", "Минимальное свечение"},
        {"Maximum Glow", "Максимальное свечение"},
        {"Threat Hitboxes", "Хитбоксы"},
        {"SOUND ESP", "ЗВУКИ"},
        {"Sound ESP", "Звуки"},
        {"Enable Sound ESP", "Показывать звуки"},
        {"Ring Color", "Цвет круга"},
        {"Local Sync", "Только слышимые"},
        {"Duration", "Длительность"},
        {"Ring Radius", "Радиус круга"},
        {"Audible Distance", "Дальность слуха"},
        {"Head Hitbox Color", "Цвет: голова"},
        {"Body Hitbox Color", "Цвет: тело"},
        {"Fill Alpha", "Прозрачность"},

        // --- chams materials --------------------------------------------
        {"Material", "Материал"},
        {"Color", "Цвет"},
        {"Wireframe", "Сетка"},
        {"Roughness", "Шероховатость"},
        {"Metalness", "Металличность"},
        {"Exponent", "Степень"},
        {"Falloff", "Спад"},
        {"Fresnel Filling", "Заливка Френеля"},
        {"Strength", "Интенсивность"},
        {"Speed", "Скорость"},
        {"Tint", "Оттенок"},
        {"Solid", "Сплошной"},
        {"Shaded", "С затенением"},
        {"Glow", "Свечение"},

        {"Glow Outline", "Контур"},
        {"Iridescent", "Перелив"},
        {"Water Flow", "Вода"},
        {"Glossy", "Глянец"},

        // --- item esp ---------------------------------------------------
        {"SETTINGS", "НАСТРОЙКИ"},
        {"FILTERS", "ФИЛЬТРЫ"},
        {"Enable Item ESP", "Включить ESP дропа"},
        {"Max Distance", "Дистанция"},
        {"Show Icon", "Иконка"},
        {"Show Item Name", "Название"},
        {"Rifles", "Винтовки"},
        {"SMGs", "ПП"},
        {"Snipers", "Снайперки"},
        {"Pistols", "Пистолеты"},
        {"Grenades", "Гранаты"},
        {"Utility", "Утилити"},

        // --- projectile esp ---------------------------------------------
        {"VISUAL ELEMENTS", "ЭЛЕМЕНТЫ"},
        {"COLORS", "ЦВЕТА"},
        {"Enable Projectiles", "Включить ESP гранат"},
        {"Display Mode", "Режим отображения"},
        {"Indicator", "Индикатор"},
        {"Text Only", "Только текст"},
        {"Show Text", "Показывать текст"},
        {"Effect Timer", "Таймер эффекта"},
        {"Effect Timer Ring", "Кольцо таймера"},
        {"Inferno Bounds", "Границы молика"},
        {"INDICATOR", "ИНДИКАТОР"},
        {"Timer Full", "Таймер: полный"},
        {"Timer Low", "Таймер: конец"},
        {"Indicator Background", "Фон индикатора"},
        {"INFERNO GRADIENT", "ГРАДИЕНТ INFERNO"},
        {"Gradient Width", "Ширина градиента"},
        {"Gradient Opacity", "Яркость градиента"},
        {"HE Grenade", "Хешка"},
        {"Flashbang", "Флешка"},
        {"Smoke", "Смок"},
        {"Molotov", "Молик"},
        {"Decoy", "Декой"},

        // --- bomb esp ---------------------------------------------------
        {"STATES", "СОСТОЯНИЯ"},
        {"SAFE ZONE (BAKED)", "БЕЗОПАСНАЯ ЗОНА"},
        {"Enable Bomb ESP", "Включить ESP бомбы"},
        {"Show Carrier", "Носитель бомбы"},
        {"Show Planted", "Установленная"},
        {"Planted Color", "Цвет установленной"},
        {"Defusing Color", "Цвет дефуза"},
        {"Panel Background", "Фон панели"},
        {"World Timer Ring", "Кольцо таймера в мире"},
        {"World Timer", "Таймер в мире"},
        {"Bomb Info Panel", "Панель информации о бомбе"},
        {"Timer Color", "Цвет таймера"},
        {"Safe Zone Contour", "Контур зоны"},
        {"Zone Color", "Цвет зоны"},
        {"Gradient Bands", "Изолинии"},
        {"Band Step", "Шаг изолиний"},

        // --- radar / world ----------------------------------------------
        {"RADAR OVERLAY", "РАДАР"},
        {"Overlay Enemy Markers", "Метки врагов"},
        {"NO FLASH (WIREFRAME)", "NO FLASH (СЕТКА)"},
        {"Enable Visual No Flash", "Включить No Flash"},
        {"Render Distance", "Дистанция"},
        {"Dimming Overlay Color", "Цвет затемнения"},
        {"Wireframe Color", "Цвет сетки"},
        {"NO SMOKE (WIREFRAME)", "NO SMOKE (СЕТКА)"},
        {"Enable Visual No Smoke", "Включить No Smoke"},
        {"Smoke Wireframe Color", "Цвет сетки в дыму"},

        // --- crosshair --------------------------------------------------
        {"CROSSHAIR SETTINGS", "ПРИЦЕЛ"},
        {"Enable Crosshair", "Включить прицел"},
        {"Draw Dot", "Точка"},
        {"Draw Lines", "Линии"},
        {"T-Style", "T-образный"},
        {"Length", "Длина"},
        {"Gap", "Зазор"},
        {"Thickness", "Толщина"},
        {"Draw Outline", "Обводка"},
        {"Primary Color", "Цвет"},
        {"Penetration Indicator", "Индикатор пенетрации"},
        {"Can Penetrate", "Пробьёт"},
        {"Cannot Penetrate", "Не пробьёт"},

        // --- misc tabs --------------------------------------------------
        {"General", "Общее"},
        {"Movement", "Мувмент"},
        {"Effects", "Эффекты"},
        {"Overlay", "Оверлей"},
        {"Lua API", "Lua API"},
        {"Configs", "Конфиги"},
        {"LUA RUNTIME", "LUA RUNTIME"},
        {"SCRIPTS", "СКРИПТЫ"},
        {"Enable Lua API", "Включить Lua API"},
        {"Script Directory", "Директория скриптов"},
        {"Open Folder", "Открыть папку"},
        {"Load Lua Script", "Загрузить Lua-скрипт"},
        {"Copy link", "Копировать ссылку"},
        {"Copy Path", "Копировать путь"},
        {"Discover Scripts", "Обновить список"},
        {"Refresh", "Обновить"},
        {"No Lua scripts found", "Lua-скрипты не найдены"},
        {"Copy scripts into the Lua directory", "Скопируйте скрипты в директорию Lua"},
        {"Autoload", "Автозагрузка"},
        {"Hot Reload", "Горячая перезагрузка"},
        {"Status", "Статус"},
        {"Runtime", "Выполнение"},
        {"Last Error", "Последняя ошибка"},
        {"Reload Script", "Перезагрузить скрипт"},
        {"Reload", "Перезагрузить"},

        // --- misc: general ----------------------------------------------
        {"AUTOMATION", "АВТОМАТИЗАЦИЯ"},
        {"Auto Accept Match", "Автопринятие матча"},
        {"GRENADES", "ГРАНАТЫ"},
        {"LINEUP HELPER", "ПОМОЩНИК РАСКИДОК"},
        {"GRENADE ASSIST", "ДОВОДКА ГРАНАТ"},
        {"TRAJECTORY", "ТРАЕКТОРИЯ"},
        {"Lineup Helper", "Раскидки"},
        {"Draw Distance", "Дистанция отрисовки"},
        {"Marker Distance", "Дистанция маркера"},
        {"Stand Radius", "Радиус точки"},
        {"Release Radius", "Точность позиции"},
        {"Height Tolerance", "Допуск по высоте"},
        {"Show Throw Type", "Тип броска"},
        {"Show Distance", "Дистанция"},
        {"Plaque Background", "Фон плашки"},
        {"Plaque Text", "Текст плашки"},
        {"Plaque Accent", "Акцент плашки"},
        {"Stand Marker", "Маркер точки"},
        {"Stand Marker Active", "Маркер точки (актив.)"},
        {"Aim Marker", "Маркер наведения"},
        {"Lineup Aim Assist", "Доводка на раскидку"},
        {"Aim Key", "Бинд доводки"},
        {"Auto Release", "Автоматический бросок"},
        {"Lock Threshold", "Порог захвата"},
        {"Settle Time", "Стабилизация"},
        {"Enemy Aim Assist", "Доводка гранаты по врагу"},
        {"Activation Key", "Бинд"},
        {"Target FOV", "FOV поиска"},
        {"Trajectory Preview", "Траектория"},
        {"Local Prediction Only", "Только свои гранаты"},
        {"Line Style", "Стиль линии"},
        {"Line Color", "Цвет линии"},
        {"Line Thickness", "Толщина линии"},
        {"Bloom", "Свечение"},
        {"Bloom Color", "Цвет свечения"},
        {"Bloom Radius", "Радиус свечения"},
        {"Bounce Points", "Точки отскока"},
        {"End Point", "Конечная точка"},
        {"Point Color", "Цвет точки"},
        {"Point Size", "Размер точки"},
        {"ENGINE", "ДВИЖОК"},
        {"FPS Limiter", "Лимит FPS"},
        {"GPU Effects", "GPU-эффекты"},
        {"Restart to change GPU effects. The base overlay uses the display adapter; off keeps 2D ESP and the menu, while chams, no flash, no smoke and bloom are disabled.", "После изменения перезапустите Vesta. Базовый оверлей использует видеокарту; выключение сохраняет 2D ESP и меню, но отключает chams, no flash, no smoke и bloom."},
        {"Maximum FPS", "Максимум FPS"},
        {"INTERFACE", "ИНТЕРФЕЙС"},
        {"LANGUAGE", "ЯЗЫК"},
        {"Language", "Язык"},
        {"DPI Scale", "Масштаб DPI"},

        // --- misc: movement ---------------------------------------------
        {"BUNNY HOP", "BUNNY HOP"},
        {"EDGE JUMP", "EDGE JUMP"},
        {"Enable Bunny Hop", "Включить Bunny Hop"},
        {"Enable Edge Jump", "Включить Edge Jump"},
        {"GAME KEY BINDS", "КНОПКИ ИГРЫ"},
        {"GAME ATTACK BINDS", "КНОПКИ СТРЕЛЬБЫ"},
        {"Back", "Назад"},
        {"Left", "Влево"},
        {"Right", "Вправо"},
        {"Duck", "Приседание"},
        {"Attack", "Выстрел"},
        {"Secondary Attack", "Доп. атака"},
        {"Reset Game Binds", "Сбросить кнопки игры"},
        {"Reset", "Сбросить"},
        {"Match these binds in the game; no automatic detection.",
         "Установите такие же кнопки в игре; автоопределения нет."},


        // --- misc: effects ----------------------------------------------
        {"BULLET TRACERS", "ТРАССЕРЫ"},
        {"Enable Bullet Tracers", "Включить трассеры"},
        {"Tracer Color", "Цвет трассера"},
        {"Fade Duration", "Время затухания"},
        {"Max Tracers", "Макс. трассеров"},
        {"Bloom Effect", "Bloom"},
        {"Draw Impact Cubes", "Метки попаданий"},
        {"Draw Trajectory Line", "Линия траектории"},
        {"Cube Size", "Размер метки"},
        {"Fade Near", "Затухание вблизи"},
        {"Fade Far", "Затухание вдали"},

        // --- misc: overlay ----------------------------------------------
        {"CAPTURE", "ЗАХВАТ ЭКРАНА"},
        {"OBS Bypass", "Обход OBS"},
        {"WATERMARK", "ВОТЕРМАРКА"},
        {"Show Watermark", "Показывать"},
        {"Show Ping", "Пинг"},
        {"Show Loss", "Лосс"},
        {"Show CPU Load", "Нагрузка CPU"},
        {"Show FPS", "FPS"},

        {"SPECTATOR LIST", "НАБЛЮДАТЕЛИ"},
        {"Show Spectators", "Показывать"},
        {"EVENT LOG", "ЖУРНАЛ СОБЫТИЙ"},
        {"Event Log", "Журнал событий"},
        {"Show Event Log", "Показывать журнал"},
        {"Maximum Entries", "Количество записей"},
        {"Events", "События"},
        {"Shots", "Выстрелы"},
        {"Hits", "Попадания"},
        {"Kills", "Убийства"},
        {"Misses", "Промахи"},
        {"Blocked", "Блокировки"},
        {"Info", "Информация"},
        {"ACTIVE BINDS", "АКТИВНЫЕ БИНДЫ"},
        {"Active Binds", "Активные бинды"},
        {"Show Active Binds", "Показывать активные бинды"},
        {"Always On Binds", "Показывать постоянные"},
        {"Hold Binds", "Показывать удерживаемые"},
        {"Toggle Binds", "Показывать переключаемые"},
        {"BOMB PANEL", "ПАНЕЛЬ БОМБЫ"},
        {"Show Bomb Info", "Показывать информацию о бомбе"},
        {"No active entries", "Нет активных записей"},
        {"Spectators", "Наблюдатели"},

        {"Steam Avatars", "Аватары Steam"},
        {"  fixed camera", "  фикс. камера"},
        {"  first person", "  от первого лица"},
        {"  third person", "  от третьего лица"},
        {"  free camera", "  свободная камера"},

        // --- misc: configs ----------------------------------------------
        {"CFG FILE", "КОНФИГ"},
        {"File Name", "Имя файла"},
        {"Export Named CFG", "Сохранить"},
        {"Save As...", "Сохранить как..."},
        {"Open CFG", "Загрузить"},
        {"Browse...", "Обзор..."},

        // --- esp editor -------------------------------------------------
        {"ESP EDITOR", "РЕДАКТОР ESP"},
        {"PREVIEW UNAVAILABLE", "ПРЕДПРОСМОТР НЕДОСТУПЕН"},

        {"Manual lineup", "Ручная раскидка"},
        {"Hold {}, release", "Зажать {}, отпустить"},
        {"Hold {}, {}, release", "Зажать {}, {}, отпустить"},
        {"LMB", "ЛКМ"},
        {"RMB", "ПКМ"},
        {"LMB+RMB", "ЛКМ+ПКМ"},
        {"m", "м"},

        {"Jump+Throw", "Джамп троу"},
        {"W+Jump+Throw", "W+Джамп троу"},
        {"Run+Jump+Throw", "Бег+Джамп троу"},
        {"Walk+Jump+Throw", "Шаг+Джамп троу"},
        {"Crouch+Jump+Throw", "Присед+Джамп троу"},
        {"Crouch+W+Jump+Throw", "Присед+W+Джамп троу"},
        {"Crouch+Run+Jump+Throw", "Присед+Бег+Джамп троу"},
        {"WJump+Throw", "W+Джамп троу"},
        {"Jump+Throw LRMB", "Джамп троу ЛКМ+ПКМ"},
        {"Jump+Throw RMB", "Джамп троу ПКМ"},
        {"W+Jump+Throw LRMB", "W+Джамп троу ЛКМ+ПКМ"},
        {"W+Jump+Throw RMB", "W+Джамп троу ПКМ"},
        {"Run+Jump+Trhow", "Бег+Джамп троу"},
        {"W+Jump+Throwv", "W+Джамп троу"},
        {"Throw", "Бросок"},
        {"Throw LRMB", "Бросок ЛКМ+ПКМ"},
        {"Throw RMB", "Бросок ПКМ"},
        {"Throw (crouch)", "Бросок в приседе"},
        {"Throw (break glass)", "Бросок (разбить стекло)"},
        {"Run+Thorw", "Бросок в беге"},
        {"Run+Throw", "Бросок в беге"},
        {"Crouch+Run+Throw", "Присед+Бросок в беге"},
        {"Go Left then W+Jump+Throw", "Влево, затем W+Джамп троу"},
        {"Go Right then W+Jump+Throw", "Вправо, затем W+Джамп троу"},
        {"Complex, move left and back and jumpthrow while running",
         "Сложная: влево-назад, джамп троу в беге"},
        {"Insta Window (no autothrow)", "Insta Window (без автоброска)"},
        {"Insta Long Door (no autothrow)", "Insta Long Door (без автоброска)"},

        // Fallback tokens, used for any combination not spelled out above.
        {"Jump", "Прыжок"},
        {"Crouch", "Присед"},
        {"Run", "Бег"},
        {"Walk", "Шаг"},
        {"Step", "Шаг"},
        {"Forward", "Вперёд"},
        // The source table spells these wrong; kept verbatim as keys.
        {"Trhow", "Бросок"},
        {"Thorw", "Бросок"},
        {"Throwv", "Бросок"},
    };

    return table;
}

const std::unordered_map<std::string_view, const char *> &chinese()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // HVH category
        {"HVH", "HVH"},
        {"HVH STATUS", "HVH 状态"},
        {"CONFIRM INJECTION", "确认注入"},
        {"INJECTION", "注入"},
        {"RAGE", "狂暴"},
        {"ANTI-AIM", "反瞄准"},
        {"TRIGGER", "扳机"},
        {"MOVEMENT", "移动"},
        {"Enable Rage", "启用狂暴"},
        {"Enable Anti-Aim", "启用反瞄准"},
        {"Enable Trigger", "启用扳机"},
        {"Mode", "模式"},
        {"Hitbox", "命中框"},
        {"Priority", "优先级"},
        {"Auto Fire", "自动开火"},
        {"Auto Wall", "自动穿墙"},
        {"Extreme Wall", "极限穿墙"},
        {"Auto Scope", "自动开镜"},
        {"Silent Aim", "静默瞄准"},
        {"Pitch", "俯仰"},
        {"Yaw Mode", "偏航模式"},
        {"Spin Speed", "旋转速度"},
        {"Jitter Min", "抖动最小值"},
        {"Jitter Max", "抖动最大值"},
        {"Fake Lag", "假延迟"},
        {"Desync", "解同步"},
        {"Delay", "延迟"},
        {"Hitchance", "命中率"},
        {"Bunny Hop", "连跳"},
        {"Auto Stop", "自动停止"},
        {"State", "状态"},
        {"Hook", "钩子"},
        {"Signatures", "特征码"},
        {"Last Error", "最近错误"},
        {"Not Injected", "未注入"},
        {"Injected", "已注入"},
        {"Ready", "就绪"},
        {"Inactive", "未激活"},
        {"Missing", "缺失"},
        {"Confirm", "确认"},
        {"Proceed", "继续"},
        {"Inject", "注入"},
        {"Abort", "中止"},
        {"Configuration", "配置"},
        {"Ejection", "弹出"},
        {"Eject", "弹出"},
        {"Nearest", "最近"},
        {"Lowest HP", "最低血量"},
        {"Upper Chest", "上胸"},
        {"Pelvis", "骨盆"},
        {"Fake Down", "假向下"},
        {"Spin", "旋转"},
        {"Jitter", "抖动"},
        {"Fake", "假身"},
        {"Inject vesta_hvh.dll into Counter-Strike 2?", "将 vesta_hvh.dll 注入到 Counter-Strike 2？"},
        {"SILENT AIM", "静默瞄准"},
        {"ACCURACY", "精度"},
        {"Enable Silent Aim", "启用静默瞄准"},
        {"PSilent", "P静默"},
        {"No Spread", "无扩散"},
        {"No Recoil", "无后坐"},
        // Navigation
        {"Aimbot", "自瞄"},
        {"Triggerbot", "扳机"},
        {"Visuals", "视觉"},
        {"Misc", "杂项"},

        // Weapon group tabs
        {"Global", "全局"},
        {"Pistol", "手枪"},
        {"SMG", "冲锋枪"},
        {"Rifle", "步枪"},
        {"Shotgun", "霰弹枪"},
        {"Sniper", "狙击枪"},
        {"Heavy", "重型"},

        // Combat cards
        {"TARGETING", "目标选择"},
        {"PENETRATION", "穿透"},
        {"VISUALIZATION", "可视化"},
        {"TRIGGERBOT CORE", "扳机核心"},
        {"ADVANCED MODE", "高级模式"},
        {"MOVEMENT", "移动"},
        {"OVERRIDE SETTINGS", "覆盖设置"},

        // Combat rows
        {"Master Switch", "总开关"},
        {"Activation", "激活方式"},
        {"Activation Mode", "激活模式"},
        {"Hold", "按住"},
        {"Always On", "始终开启"},
        {"Toggle", "切换"},
        {"Damage Override", "伤害覆盖"},
        {"Override Damage", "覆盖伤害"},
        {"Checks", "检查"},
        {"Jump", "跳跃"},
        {"Flash", "闪光"},
        {"Airborne", "空中"},
        {"Flashed", "被闪"},
        {"Threshold", "阈值"},
        {"Smoke", "烟雾"},
        {"Walls", "墙体"},
        {"Block", "阻挡"},
        {"Penetration", "穿透"},
        {"Ignore", "忽略"},
        {"Trigger Key", "扳机键"},
        {"FOV", "视野"},
        {"FOV Profile", "视野配置"},
        {"Radius", "半径"},
        {"Max Radius", "最大半径"},
        {"Min Radius", "最小半径"},
        {"Full Size At", "满尺寸距离"},
        {"Min Size At", "最小尺寸距离"},
        {"Advanced", "高级"},
        {"Fixed", "固定"},
        {"Distance", "距离"},
        {"Target", "目标"},
        {"Near Distance", "近距离"},
        {"Near FOV", "近视野"},
        {"Far Distance", "远距离"},
        {"Far FOV", "远视野"},
        {"Acquisition Area", "获取范围"},
        {"Target Point", "目标点"},
        {"Show FOV", "显示视野"},
        {"Visualization", "可视化"},
        {"Smoothing", "平滑"},
        {"Humanize", "拟人化"},
        {"Humanizer Tuning", "拟人化调校"},
        {"Humanizer Profile", "拟人化配置"},
        {"Motion", "运动"},
        {"Behavior", "行为"},
        {"Gravity", "重力"},
        {"Wind", "风力"},
        {"Max Step", "最大步长"},
        {"Damping", "阻尼"},
        {"Reaction Min", "最小反应"},
        {"Reaction Max", "最大反应"},
        {"Curve", "曲线"},
        {"Overshoot Chance", "过冲概率"},
        {"Overshoot Amount", "过冲幅度"},
        {"Jitter", "抖动"},
        {"Deadzone", "死区"},
        {"Hitboxes", "命中框"},
        {"Multi-Point", "多点"},
        {"Cap Points", "顶点"},
        {"Side Points", "侧点"},
        {"Head Scale", "头部缩放"},
        {"Body Scale", "身体缩放"},
        {"Limbs Scale", "四肢缩放"},
        {"Prediction", "预判"},
        {"Max Horizon", "最大预判"},
        {"Acceleration", "加速度"},
        {"RCS", "后坐力控制"},
        {"Start Bullet", "起始子弹"},
        {"Pitch Strength", "俯仰强度"},
        {"Yaw Strength", "偏航强度"},
        {"Humanization", "拟人化"},
        {"Response", "响应"},
        {"Gain Randomness", "增益随机"},
        {"Drift", "漂移"},
        {"Correction Time", "修正时间"},
        {"Smoothness", "平滑度"},
        {"Strength Variation", "强度变化"},
        {"Path Drift", "路径漂移"},
        {"Wall Policy", "墙体策略"},
        {"Only Visible", "仅可见"},
        {"Shot Timing", "开火时机"},
        {"Randomize", "随机化"},
        {"Outlier Chance", "离群概率"},
        {"Outlier Delay", "离群延迟"},
        {"Lethal Only", "仅致命"},
        {"R8 Readiness", "R8 就绪"},
        {"Release Margin", "释放余量"},
        {"Key", "按键"},
        {"Visible Only", "仅可见"},
        {"Predictive", "预判"},
        {"Recoil Sync", "后坐力同步"},
        {"Auto Wall", "自动穿墙"},
        {"Min Damage", "最小伤害"},
        {"Draw FOV Circle", "绘制视野圈"},
        {"Mode", "模式"},

        // Interface / palette
        {"Interface Colors", "界面颜色"},
        {"Typography", "排版"},
        {"Primary Text", "主文本"},
        {"Muted Text", "次要文本"},
        {"Surfaces", "表面"},
        {"Menu Background", "菜单背景"},
        {"Controls", "控件"},
        {"Containers", "容器"},
        {"Popups", "弹窗"},
        {"Interaction", "交互"},
        {"Accent", "强调色"},
        {"Hover", "悬停"},
        {"Borders", "边框"},
        {"Seed Type", "种子类型"},
        {"Hitchance", "命中率"},
        {"Delay (ms)", "延迟 (毫秒)"},
        {"Reaction Time (ms)", "反应时间 (毫秒)"},
        {"Auto Stop", "自动急停"},
        {"Early Auto Stop", "提前自动急停"},
        {"Delay Before", "之前延迟"},
        {"Delay After", "之后延迟"},
        {"Randomize (+-)", "随机化 (+-)"},
        {"Inherit Global Settings", "继承全局设置"},

        // Shared option values
        {"None", "无"},
        {"All", "全部"},
        {"Restricted", "受限"},
        {"Unrestricted", "不受限"},
        {"Head", "头部"},
        {"Body", "身体"},
        {"Arms", "手臂"},
        {"Legs", "腿部"},

        // Visuals tabs
        {"Players", "玩家"},
        {"Items", "物品"},
        {"Projectiles", "投掷物"},
        {"Bomb", "炸弹"},
        {"Radar", "雷达"},
        {"World", "世界"},
        {"Crosshair", "准星"},

        // Player ESP
        {"Player Names", "玩家名称"},
        {"Player Health", "玩家生命"},
        {"Player Armor", "玩家护甲"},
        {"Player Weapon", "玩家武器"},
        {"Grenade Markers", "手雷标记"},
        {"Grenade Trajectories", "手雷轨迹"},
        {"Grenade Zones", "手雷区域"},
        {"Information Scale", "信息缩放"},
        {"Overlay Enemy Markers", "覆盖敌方标记"},
        {"Enemy Marker", "敌方标记"},
        {"View Direction", "视线方向"},
        {"Status Text", "状态文本"},
        {"Marker Scale", "标记缩放"},
        {"Text Outline", "文字描边"},
        {"HE Color", "高爆颜色"},
        {"Flash Color", "闪光颜色"},
        {"Smoke Color", "烟雾颜色"},
        {"Molotov Color", "燃烧弹颜色"},
        {"Decoy Color", "诱饵弹颜色"},
        {"Line Thickness", "线宽"},
        {"End Point Size", "终点大小"},
        {"Fill Opacity", "填充不透明度"},
        {"Outline Opacity", "描边不透明度"},
        {"In-Game Avatars", "游戏内头像"},
        {"Outline Color", "描边颜色"},
        {"Outline Thickness", "描边粗细"},

        {"MASTER", "主控"},
        {"BOUNDING BOX", "边界框"},
        {"DETAILS", "详情"},
        {"SKELETON & HITBOXES", "骨架与命中框"},
        {"Enable Player ESP", "启用玩家透视"},
        {"Legit Sync", "合法同步"},
        {"Spectator Sync", "观战者同步"},
        {"Direct Visibility", "直接可见"},
        {"Radar Spotted", "雷达标记"},
        {"Audible Sounds", "可听声音"},
        {"Radar Hold", "雷达按住"},
        {"Sound Hold", "声音按住"},
        {"Hearing Distance", "听觉距离"},
        {"Pulse Minimum", "脉冲最小"},
        {"Pulse Maximum", "脉冲最大"},
        {"Pulse Period", "脉冲周期"},
        {"Show Box", "显示方框"},
        {"Style", "样式"},
        {"Full", "完整"},
        {"Cornered", "角框"},
        {"Corner Length", "角长度"},
        {"Background Fill", "背景填充"},
        {"Box Visible Color", "方框可见颜色"},
        {"Box Occluded Color", "方框遮挡颜色"},
        {"Fill Visible Color", "填充可见颜色"},
        {"Fill Occluded Color", "填充遮挡颜色"},
        {"Show Name", "显示名称"},
        {"Show Weapon", "显示武器"},
        {"Ammo Indicator", "弹药指示"},
        {"Exact Ammo Count", "精确弹药数"},
        {"Empty Color", "空弹颜色"},
        {"Bomb Damage", "炸弹伤害"},
        {"Health Bar", "生命条"},
        {"Ammo Bar", "弹药条"},
        {"Info Flags", "信息标记"},
        {"Chams", "模型透视"},
        {"Antialiasing", "抗锯齿"},
        {"Model Glow", "模型发光"},
        {"Glow Color", "发光颜色"},
        {"Glow Radius", "发光半径"},
        {"Glow Strength", "发光强度"},
        {"Glow Layers", "发光层数"},
        {"Death Shatter", "死亡碎裂"},
        {"On Hit Chams", "命中模型"},
        {"Kill Particles", "击杀粒子"},
        {"Particle Color", "粒子颜色"},
        {"Particle Duration", "粒子持续时间"},
        {"Particle Size", "粒子大小"},
        {"Particle Count", "粒子数量"},
        {"On Shot Chams", "开火模型"},
        {"Ghost Duration", "残影持续时间"},
        {"Ghost Appearance", "残影外观"},
        {"Occlusion", "遮挡"},
        {"Dynamic Doors", "动态门"},
        {"Smoke Occlusion", "烟雾遮挡"},
        {"Chams Visible", "可见模型"},
        {"Chams Occluded", "遮挡模型"},
        {"Show Skeleton", "显示骨架"},
        {"Show Head Circle", "显示头部圆圈"},
        {"Show View Line", "显示视线"},
        {"Offscreen Arrows", "屏幕外箭头"},
        {"Arrow Color", "箭头颜色"},
        {"Arrow Size", "箭头大小"},
        {"Arrow Radius", "箭头半径"},
        {"Bloom Speed", "脉冲速度"},
        {"Minimum Glow", "最小发光"},
        {"Maximum Glow", "最大发光"},
        {"Threat Hitboxes", "威胁命中框"},

        // Sound ESP
        {"SOUND ESP", "声音透视"},
        {"Sound ESP", "声音透视"},
        {"Enable Sound ESP", "启用声音透视"},
        {"Ring Color", "圆环颜色"},
        {"Local Sync", "本地同步"},
        {"Duration", "持续时间"},
        {"Ring Radius", "圆环半径"},
        {"Audible Distance", "可听距离"},
        {"Head Hitbox Color", "头部命中框颜色"},
        {"Body Hitbox Color", "身体命中框颜色"},
        {"Fill Alpha", "填充透明度"},

        // Chams materials
        {"Material", "材质"},
        {"Color", "颜色"},
        {"Wireframe", "线框"},
        {"Roughness", "粗糙度"},
        {"Metalness", "金属度"},
        {"Exponent", "指数"},
        {"Falloff", "衰减"},
        {"Fresnel Filling", "菲涅尔填充"},
        {"Strength", "强度"},
        {"Speed", "速度"},
        {"Tint", "色调"},
        {"Solid", "实心"},
        {"Shaded", "着色"},
        {"Glow", "发光"},
        {"Glow Outline", "发光描边"},
        {"Iridescent", "彩虹"},
        {"Water Flow", "水流"},
        {"Glossy", "光泽"},

        // Item ESP
        {"SETTINGS", "设置"},
        {"FILTERS", "过滤"},
        {"Enable Item ESP", "启用物品透视"},
        {"Max Distance", "最大距离"},
        {"Show Icon", "显示图标"},
        {"Show Item Name", "显示物品名称"},
        {"Rifles", "步枪"},
        {"SMGs", "冲锋枪"},
        {"Snipers", "狙击枪"},
        {"Pistols", "手枪"},
        {"Grenades", "手雷"},
        {"Utility", "道具"},

        // Projectile ESP
        {"VISUAL ELEMENTS", "视觉元素"},
        {"COLORS", "颜色"},
        {"Enable Projectiles", "启用投掷物"},
        {"Display Mode", "显示模式"},
        {"Indicator", "指示器"},
        {"Text Only", "仅文字"},
        {"Show Text", "显示文字"},
        {"Effect Timer", "效果计时器"},
        {"Effect Timer Ring", "效果计时环"},
        {"Inferno Bounds", "燃烧范围"},
        {"INDICATOR", "指示器"},
        {"Timer Full", "计时满"},
        {"Timer Low", "计时低"},
        {"Indicator Background", "指示器背景"},
        {"INFERNO GRADIENT", "燃烧渐变"},
        {"Gradient Width", "渐变宽度"},
        {"Gradient Opacity", "渐变不透明度"},
        {"HE Grenade", "高爆手雷"},
        {"Flashbang", "闪光弹"},
        {"Smoke", "烟雾弹"},
        {"Molotov", "燃烧弹"},
        {"Decoy", "诱饵弹"},

        // Bomb ESP
        {"STATES", "状态"},
        {"SAFE ZONE (BAKED)", "安全区 (预计算)"},
        {"Enable Bomb ESP", "启用炸弹透视"},
        {"Show Carrier", "显示携带者"},
        {"Show Planted", "显示已安放"},
        {"Planted Color", "已安放颜色"},
        {"Defusing Color", "拆弹颜色"},
        {"Panel Background", "面板背景"},
        {"World Timer Ring", "世界计时环"},
        {"World Timer", "世界计时器"},
        {"Bomb Info Panel", "炸弹信息面板"},
        {"Timer Color", "计时器颜色"},
        {"Safe Zone Contour", "安全区轮廓"},
        {"Zone Color", "区域颜色"},
        {"Gradient Bands", "渐变条带"},
        {"Band Step", "条带间距"},

        // Radar / world
        {"RADAR OVERLAY", "雷达覆盖"},
        {"NO FLASH (WIREFRAME)", "无闪光 (线框)"},
        {"Enable Visual No Flash", "启用视觉无闪光"},
        {"Render Distance", "渲染距离"},
        {"Dimming Overlay Color", "变暗覆盖颜色"},
        {"Wireframe Color", "线框颜色"},
        {"NO SMOKE (WIREFRAME)", "无烟雾 (线框)"},
        {"Enable Visual No Smoke", "启用视觉无烟雾"},
        {"Smoke Wireframe Color", "烟雾线框颜色"},

        // Crosshair
        {"CROSSHAIR SETTINGS", "准星设置"},
        {"Enable Crosshair", "启用准星"},
        {"Draw Dot", "绘制点"},
        {"Draw Lines", "绘制线"},
        {"T-Style", "T 形"},
        {"Length", "长度"},
        {"Gap", "间隙"},
        {"Thickness", "粗细"},
        {"Draw Outline", "绘制描边"},
        {"Primary Color", "主颜色"},
        {"Penetration Indicator", "穿透指示"},
        {"Can Penetrate", "可穿透"},
        {"Cannot Penetrate", "不可穿透"},

        // Misc tabs
        {"General", "通用"},
        {"Movement", "移动"},
        {"Effects", "效果"},
        {"Overlay", "覆盖"},
        {"Lua API", "Lua API"},
        {"Configs", "配置"},

        // Misc - Lua
        {"LUA RUNTIME", "Lua 运行时"},
        {"SCRIPTS", "脚本"},
        {"Enable Lua API", "启用 Lua API"},
        {"Script Directory", "脚本目录"},
        {"Open Folder", "打开文件夹"},
        {"Load Lua Script", "加载 Lua 脚本"},
        {"Copy link", "复制链接"},
        {"Copy Path", "复制路径"},
        {"Discover Scripts", "发现脚本"},
        {"Refresh", "刷新"},
        {"No Lua scripts found", "未找到 Lua 脚本"},
        {"Copy scripts into the Lua directory", "将脚本放入 Lua 目录"},
        {"Autoload", "自动加载"},
        {"Hot Reload", "热重载"},
        {"Status", "状态"},
        {"Runtime", "运行时"},
        {"Last Error", "最后错误"},
        {"Reload Script", "重载脚本"},
        {"Reload", "重载"},

        // Misc - General
        {"AUTOMATION", "自动化"},
        {"Auto Accept Match", "自动接受对局"},
        {"GRENADES", "手雷"},
        {"LINEUP HELPER", "站位助手"},
        {"GRENADE ASSIST", "手雷辅助"},
        {"TRAJECTORY", "轨迹"},
        {"Lineup Helper", "站位助手"},
        {"Draw Distance", "绘制距离"},
        {"Marker Distance", "标记距离"},
        {"Stand Radius", "站立半径"},
        {"Release Radius", "释放半径"},
        {"Height Tolerance", "高度容差"},
        {"Show Throw Type", "显示投掷类型"},
        {"Show Distance", "显示距离"},
        {"Plaque Background", "标牌背景"},
        {"Plaque Text", "标牌文字"},
        {"Plaque Accent", "标牌强调色"},
        {"Stand Marker", "站立标记"},
        {"Stand Marker Active", "站立标记激活"},
        {"Aim Marker", "瞄准标记"},
        {"Lineup Aim Assist", "站位瞄准辅助"},
        {"Aim Key", "瞄准键"},
        {"Auto Release", "自动释放"},
        {"Lock Threshold", "锁定阈值"},
        {"Settle Time", "稳定时间"},
        {"Enemy Aim Assist", "敌人瞄准辅助"},
        {"Activation Key", "激活键"},
        {"Target FOV", "目标视野"},
        {"Trajectory Preview", "轨迹预览"},
        {"Local Prediction Only", "仅本地预判"},
        {"Line Style", "线条样式"},
        {"Line Color", "线条颜色"},
        {"Bloom", "脉冲"},
        {"Bloom Color", "脉冲颜色"},
        {"Bloom Radius", "脉冲半径"},
        {"Bounce Points", "弹跳点"},
        {"End Point", "终点"},
        {"Point Color", "点颜色"},
        {"Point Size", "点大小"},

        // Misc - Engine / Interface
        {"ENGINE", "引擎"},
        {"FPS Limiter", "FPS 限制"},
        {"GPU Effects", "GPU 特效"},
        {"Restart to change GPU effects. The base overlay uses the display adapter; off keeps 2D ESP and the menu, while chams, no flash, no smoke and bloom are disabled.", "更改 GPU 特效后需重启。基础覆盖层使用显示适配器；关闭后仍保留 2D 透视和菜单，但模型透视、无闪光、无烟雾和脉冲将被禁用。"},
        {"Maximum FPS", "最大 FPS"},
        {"INTERFACE", "界面"},
        {"LANGUAGE", "语言"},
        {"Language", "语言"},
        {"DPI Scale", "DPI 缩放"},

        // Misc - Movement
        {"BUNNY HOP", "连跳"},
        {"EDGE JUMP", "边缘跳"},
        {"Enable Bunny Hop", "启用连跳"},
        {"Enable Edge Jump", "启用边缘跳"},
        {"GAME KEY BINDS", "游戏按键绑定"},
        {"GAME ATTACK BINDS", "游戏攻击绑定"},
        {"Back", "后退"},
        {"Left", "左"},
        {"Right", "右"},
        {"Duck", "下蹲"},
        {"Attack", "攻击"},
        {"Secondary Attack", "副攻击"},
        {"Reset Game Binds", "重置游戏绑定"},
        {"Reset", "重置"},
        {"Match these binds in the game; no automatic detection.", "请在游戏中手动设置这些按键；本工具不会自动检测。"},

        // Misc - Effects
        {"BULLET TRACERS", "子弹轨迹"},
        {"Enable Bullet Tracers", "启用子弹轨迹"},
        {"Tracer Color", "轨迹颜色"},
        {"Fade Duration", "淡出持续时间"},
        {"Max Tracers", "最大轨迹数"},
        {"Bloom Effect", "脉冲效果"},
        {"Draw Impact Cubes", "绘制命中方块"},
        {"Draw Trajectory Line", "绘制弹道线"},
        {"Cube Size", "方块大小"},
        {"Fade Near", "近端淡出"},
        {"Fade Far", "远端淡出"},

        // Misc - Overlay
        {"CAPTURE", "捕获"},
        {"OBS Bypass", "OBS 绕过"},
        {"WATERMARK", "水印"},
        {"Show Watermark", "显示水印"},
        {"Show Ping", "显示延迟"},
        {"Show Loss", "显示丢包"},
        {"Show CPU Load", "显示 CPU 占用"},
        {"Show FPS", "显示 FPS"},
        {"SPECTATOR LIST", "观战者列表"},
        {"Show Spectators", "显示观战者"},
        {"EVENT LOG", "事件日志"},
        {"Event Log", "事件日志"},
        {"Show Event Log", "显示事件日志"},
        {"Maximum Entries", "最大条目"},
        {"Events", "事件"},
        {"Shots", "射击"},
        {"Hits", "命中"},
        {"Kills", "击杀"},
        {"Misses", "未命中"},
        {"Blocked", "被阻挡"},
        {"Info", "信息"},
        {"ACTIVE BINDS", "活动绑定"},
        {"Active Binds", "活动绑定"},
        {"Show Active Binds", "显示活动绑定"},
        {"Always On Binds", "始终开启绑定"},
        {"Hold Binds", "按住绑定"},
        {"Toggle Binds", "切换绑定"},
        {"BOMB PANEL", "炸弹面板"},
        {"Show Bomb Info", "显示炸弹信息"},
        {"No active entries", "无活动条目"},
        {"Spectators", "观战者"},
        {"Steam Avatars", "Steam 头像"},
        {"  fixed camera", "  固定视角"},
        {"  first person", "  第一人称"},
        {"  third person", "  第三人称"},
        {"  free camera", "  自由视角"},

        // Misc - Configs
        {"CFG FILE", "配置文件"},
        {"File Name", "文件名"},
        {"Export Named CFG", "导出命名配置"},
        {"Save As...", "另存为..."},
        {"Open CFG", "打开配置"},
        {"Browse...", "浏览..."},

        // ESP editor
        {"ESP EDITOR", "ESP 编辑器"},
        {"PREVIEW UNAVAILABLE", "预览不可用"},

        // Nade helper action tokens
        {"Manual lineup", "手动站位"},
        {"Hold {}, release", "按住 {}, 松开"},
        {"Hold {}, {}, release", "按住 {}, {}, 松开"},
        {"LMB", "左键"},
        {"RMB", "右键"},
        {"LMB+RMB", "左键+右键"},
        {"m", "米"},
        {"Jump+Throw", "跳跃+投掷"},
        {"W+Jump+Throw", "W+跳跃+投掷"},
        {"Run+Jump+Throw", "跑动+跳跃+投掷"},
        {"Walk+Jump+Throw", "走动+跳跃+投掷"},
        {"Crouch+Jump+Throw", "下蹲+跳跃+投掷"},
        {"Crouch+W+Jump+Throw", "下蹲+W+跳跃+投掷"},
        {"Crouch+Run+Jump+Throw", "下蹲+跑动+跳跃+投掷"},
        {"WJump+Throw", "W跳跃+投掷"},
        {"Jump+Throw LRMB", "跳跃+投掷 左右键"},
        {"Jump+Throw RMB", "跳跃+投掷 右键"},
        {"W+Jump+Throw LRMB", "W+跳跃+投掷 左右键"},
        {"W+Jump+Throw RMB", "W+跳跃+投掷 右键"},
        {"Run+Jump+Trhow", "跑动+跳跃+投掷"},
        {"W+Jump+Throwv", "W+跳跃+投掷"},
        {"Throw", "投掷"},
        {"Throw LRMB", "投掷 左右键"},
        {"Throw RMB", "投掷 右键"},
        {"Throw (crouch)", "投掷 (下蹲)"},
        {"Throw (break glass)", "投掷 (破窗)"},
        {"Run+Thorw", "跑动+投掷"},
        {"Run+Throw", "跑动+投掷"},
        {"Crouch+Run+Throw", "下蹲+跑动+投掷"},
        {"Go Left then W+Jump+Throw", "先左移再 W+跳跃+投掷"},
        {"Go Right then W+Jump+Throw", "先右移再 W+跳跃+投掷"},
        {"Complex, move left and back and jumpthrow while running", "复杂：向左后移动并在跑动中跳跃投掷"},
        {"Insta Window (no autothrow)", "快速窗口 (不自动投掷)"},
        {"Insta Long Door (no autothrow)", "快速长门 (不自动投掷)"},

        // Fallback tokens
        {"Crouch", "下蹲"},
        {"Run", "跑动"},
        {"Walk", "走动"},
        {"Step", "步伐"},
        {"Forward", "前进"},
        {"Trhow", "投掷"},
        {"Thorw", "投掷"},
        {"Throwv", "投掷"},
    };

    return table;
}

const std::unordered_map<std::string_view, const char *> &traditional()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // HVH category
        {"HVH", "HVH"},
        {"HVH STATUS", "HVH 狀態"},
        {"CONFIRM INJECTION", "確認注入"},
        {"INJECTION", "注入"},
        {"RAGE", "狂暴"},
        {"ANTI-AIM", "反瞄準"},
        {"TRIGGER", "扳機"},
        {"MOVEMENT", "移動"},
        {"Enable Rage", "啟用狂暴"},
        {"Enable Anti-Aim", "啟用反瞄準"},
        {"Enable Trigger", "啟用扳機"},
        {"Mode", "模式"},
        {"Hitbox", "命中框"},
        {"Priority", "優先級"},
        {"Auto Fire", "自動開火"},
        {"Auto Wall", "自動穿牆"},
        {"Extreme Wall", "極限穿牆"},
        {"Auto Scope", "自動開鏡"},
        {"Silent Aim", "靜默瞄準"},
        {"Pitch", "俯仰"},
        {"Yaw Mode", "偏航模式"},
        {"Spin Speed", "旋轉速度"},
        {"Jitter Min", "抖動最小值"},
        {"Jitter Max", "抖動最大值"},
        {"Fake Lag", "假延遲"},
        {"Desync", "解同步"},
        {"Delay", "延遲"},
        {"Hitchance", "命中率"},
        {"Bunny Hop", "連跳"},
        {"Auto Stop", "自動停止"},
        {"State", "狀態"},
        {"Hook", "鉤子"},
        {"Signatures", "特徵碼"},
        {"Last Error", "最近錯誤"},
        {"Not Injected", "未注入"},
        {"Injected", "已注入"},
        {"Ready", "就緒"},
        {"Inactive", "未啟用"},
        {"Missing", "缺失"},
        {"Confirm", "確認"},
        {"Proceed", "繼續"},
        {"Inject", "注入"},
        {"Abort", "中止"},
        {"Configuration", "設定"},
        {"Ejection", "彈出"},
        {"Eject", "彈出"},
        {"Nearest", "最近"},
        {"Lowest HP", "最低血量"},
        {"Upper Chest", "上胸"},
        {"Pelvis", "骨盆"},
        {"Fake Down", "假向下"},
        {"Spin", "旋轉"},
        {"Jitter", "抖動"},
        {"Fake", "假身"},
        {"Inject vesta_hvh.dll into Counter-Strike 2?", "將 vesta_hvh.dll 注入到 Counter-Strike 2？"},
        {"SILENT AIM", "靜默瞄準"},
        {"ACCURACY", "精準度"},
        {"Enable Silent Aim", "啟用靜默瞄準"},
        {"PSilent", "P靜默"},
        {"No Spread", "無擴散"},
        {"No Recoil", "無後座"},
        // Navigation
        {"Aimbot", "自瞄"},
        {"Triggerbot", "扳機"},
        {"Visuals", "視覺"},
        {"Misc", "雜項"},

        // Weapon group tabs
        {"Global", "全域"},
        {"Pistol", "手槍"},
        {"SMG", "衝鋒槍"},
        {"Rifle", "步槍"},
        {"Shotgun", "霰彈槍"},
        {"Sniper", "狙擊槍"},
        {"Heavy", "重型"},

        // Combat cards
        {"TARGETING", "目標選擇"},
        {"PENETRATION", "穿透"},
        {"VISUALIZATION", "視覺化"},
        {"TRIGGERBOT CORE", "扳機核心"},
        {"ADVANCED MODE", "高級模式"},
        {"MOVEMENT", "移動"},
        {"OVERRIDE SETTINGS", "覆蓋設定"},

        // Combat rows
        {"Master Switch", "總開關"},
        {"Activation", "啟用方式"},
        {"Activation Mode", "啟用模式"},
        {"Hold", "按住"},
        {"Always On", "始終開啟"},
        {"Toggle", "切換"},
        {"Damage Override", "傷害覆蓋"},
        {"Override Damage", "覆蓋傷害"},
        {"Checks", "檢查"},
        {"Jump", "跳躍"},
        {"Flash", "閃光"},
        {"Airborne", "空中"},
        {"Flashed", "被閃"},
        {"Threshold", "閾值"},
        {"Smoke", "煙霧"},
        {"Walls", "牆體"},
        {"Block", "阻擋"},
        {"Penetration", "穿透"},
        {"Ignore", "忽略"},
        {"Trigger Key", "扳機鍵"},
        {"FOV", "視野"},
        {"FOV Profile", "視野配置"},
        {"Radius", "半徑"},
        {"Max Radius", "最大半徑"},
        {"Min Radius", "最小半徑"},
        {"Full Size At", "滿尺寸距離"},
        {"Min Size At", "最小尺寸距離"},
        {"Advanced", "高級"},
        {"Fixed", "固定"},
        {"Distance", "距離"},
        {"Target", "目標"},
        {"Near Distance", "近距離"},
        {"Near FOV", "近視野"},
        {"Far Distance", "遠距離"},
        {"Far FOV", "遠視野"},
        {"Acquisition Area", "獲取範圍"},
        {"Target Point", "目標點"},
        {"Show FOV", "顯示視野"},
        {"Visualization", "視覺化"},
        {"Smoothing", "平滑"},
        {"Humanize", "擬人化"},
        {"Humanizer Tuning", "擬人化調校"},
        {"Humanizer Profile", "擬人化配置"},
        {"Motion", "運動"},
        {"Behavior", "行為"},
        {"Gravity", "重力"},
        {"Wind", "風力"},
        {"Max Step", "最大步長"},
        {"Damping", "阻尼"},
        {"Reaction Min", "最小反應"},
        {"Reaction Max", "最大反應"},
        {"Curve", "曲線"},
        {"Overshoot Chance", "過衝機率"},
        {"Overshoot Amount", "過衝幅度"},
        {"Jitter", "抖動"},
        {"Deadzone", "死區"},
        {"Hitboxes", "命中框"},
        {"Multi-Point", "多點"},
        {"Cap Points", "頂點"},
        {"Side Points", "側點"},
        {"Head Scale", "頭部縮放"},
        {"Body Scale", "身體縮放"},
        {"Limbs Scale", "四肢縮放"},
        {"Prediction", "預判"},
        {"Max Horizon", "最大預判"},
        {"Acceleration", "加速度"},
        {"RCS", "後坐力控制"},
        {"Start Bullet", "起始子彈"},
        {"Pitch Strength", "俯仰強度"},
        {"Yaw Strength", "偏航強度"},
        {"Humanization", "擬人化"},
        {"Response", "響應"},
        {"Gain Randomness", "增益隨機"},
        {"Drift", "漂移"},
        {"Correction Time", "修正時間"},
        {"Smoothness", "平滑度"},
        {"Strength Variation", "強度變化"},
        {"Path Drift", "路徑漂移"},
        {"Wall Policy", "牆體策略"},
        {"Only Visible", "僅可見"},
        {"Shot Timing", "開火時機"},
        {"Randomize", "隨機化"},
        {"Outlier Chance", "離群機率"},
        {"Outlier Delay", "離群延遲"},
        {"Lethal Only", "僅致命"},
        {"R8 Readiness", "R8 就緒"},
        {"Release Margin", "釋放餘量"},
        {"Key", "按鍵"},
        {"Visible Only", "僅可見"},
        {"Predictive", "預判"},
        {"Recoil Sync", "後坐力同步"},
        {"Auto Wall", "自動穿牆"},
        {"Min Damage", "最小傷害"},
        {"Draw FOV Circle", "繪製視野圈"},
        {"Mode", "模式"},

        // Interface / palette
        {"Interface Colors", "介面顏色"},
        {"Typography", "排版"},
        {"Primary Text", "主文字"},
        {"Muted Text", "次要文字"},
        {"Surfaces", "表面"},
        {"Menu Background", "選單背景"},
        {"Controls", "控制項"},
        {"Containers", "容器"},
        {"Popups", "彈出視窗"},
        {"Interaction", "互動"},
        {"Accent", "強調色"},
        {"Hover", "懸停"},
        {"Borders", "邊框"},
        {"Seed Type", "種子類型"},
        {"Hitchance", "命中率"},
        {"Delay (ms)", "延遲 (毫秒)"},
        {"Reaction Time (ms)", "反應時間 (毫秒)"},
        {"Auto Stop", "自動急停"},
        {"Early Auto Stop", "提前自動急停"},
        {"Delay Before", "之前延遲"},
        {"Delay After", "之後延遲"},
        {"Randomize (+-)", "隨機化 (+-)"},
        {"Inherit Global Settings", "繼承全域設定"},

        // Shared option values
        {"None", "無"},
        {"All", "全部"},
        {"Restricted", "受限"},
        {"Unrestricted", "不受限"},
        {"Head", "頭部"},
        {"Body", "身體"},
        {"Arms", "手臂"},
        {"Legs", "腿部"},

        // Visuals tabs
        {"Players", "玩家"},
        {"Items", "物品"},
        {"Projectiles", "投擲物"},
        {"Bomb", "炸彈"},
        {"Radar", "雷達"},
        {"World", "世界"},
        {"Crosshair", "準星"},

        // Player ESP
        {"Player Names", "玩家名稱"},
        {"Player Health", "玩家生命"},
        {"Player Armor", "玩家護甲"},
        {"Player Weapon", "玩家武器"},
        {"Grenade Markers", "手雷標記"},
        {"Grenade Trajectories", "手雷軌跡"},
        {"Grenade Zones", "手雷區域"},
        {"Information Scale", "資訊縮放"},
        {"Overlay Enemy Markers", "覆蓋敵方標記"},
        {"Enemy Marker", "敵方標記"},
        {"View Direction", "視線方向"},
        {"Status Text", "狀態文字"},
        {"Marker Scale", "標記縮放"},
        {"Text Outline", "文字描邊"},
        {"HE Color", "高爆顏色"},
        {"Flash Color", "閃光顏色"},
        {"Smoke Color", "煙霧顏色"},
        {"Molotov Color", "燃燒彈顏色"},
        {"Decoy Color", "誘餌彈顏色"},
        {"Line Thickness", "線寬"},
        {"End Point Size", "終點大小"},
        {"Fill Opacity", "填充不透明度"},
        {"Outline Opacity", "描邊不透明度"},
        {"In-Game Avatars", "遊戲內頭像"},
        {"Outline Color", "描邊顏色"},
        {"Outline Thickness", "描邊粗細"},

        {"MASTER", "主控"},
        {"BOUNDING BOX", "邊界框"},
        {"DETAILS", "詳情"},
        {"SKELETON & HITBOXES", "骨骼與命中框"},
        {"Enable Player ESP", "啟用玩家透視"},
        {"Legit Sync", "合法同步"},
        {"Spectator Sync", "觀戰者同步"},
        {"Direct Visibility", "直接可見"},
        {"Radar Spotted", "雷達標記"},
        {"Audible Sounds", "可聽聲音"},
        {"Radar Hold", "雷達按住"},
        {"Sound Hold", "聲音按住"},
        {"Hearing Distance", "聽覺距離"},
        {"Pulse Minimum", "脈衝最小"},
        {"Pulse Maximum", "脈衝最大"},
        {"Pulse Period", "脈衝週期"},
        {"Show Box", "顯示方框"},
        {"Style", "樣式"},
        {"Full", "完整"},
        {"Cornered", "角框"},
        {"Corner Length", "角長度"},
        {"Background Fill", "背景填充"},
        {"Box Visible Color", "方框可見顏色"},
        {"Box Occluded Color", "方框遮蔽顏色"},
        {"Fill Visible Color", "填充可見顏色"},
        {"Fill Occluded Color", "填充遮蔽顏色"},
        {"Show Name", "顯示名稱"},
        {"Show Weapon", "顯示武器"},
        {"Ammo Indicator", "彈藥指示"},
        {"Exact Ammo Count", "精確彈藥數"},
        {"Empty Color", "空彈顏色"},
        {"Bomb Damage", "炸彈傷害"},
        {"Health Bar", "生命條"},
        {"Ammo Bar", "彈藥條"},
        {"Info Flags", "資訊標記"},
        {"Chams", "模型透視"},
        {"Antialiasing", "抗鋸齒"},
        {"Model Glow", "模型發光"},
        {"Glow Color", "發光顏色"},
        {"Glow Radius", "發光半徑"},
        {"Glow Strength", "發光強度"},
        {"Glow Layers", "發光層數"},
        {"Death Shatter", "死亡碎裂"},
        {"On Hit Chams", "命中模型"},
        {"Kill Particles", "擊殺粒子"},
        {"Particle Color", "粒子顏色"},
        {"Particle Duration", "粒子持續時間"},
        {"Particle Size", "粒子大小"},
        {"Particle Count", "粒子數量"},
        {"On Shot Chams", "開火模型"},
        {"Ghost Duration", "殘影持續時間"},
        {"Ghost Appearance", "殘影外觀"},
        {"Occlusion", "遮蔽"},
        {"Dynamic Doors", "動態門"},
        {"Smoke Occlusion", "煙霧遮蔽"},
        {"Chams Visible", "可見模型"},
        {"Chams Occluded", "遮蔽模型"},
        {"Show Skeleton", "顯示骨骼"},
        {"Show Head Circle", "顯示頭部圓圈"},
        {"Show View Line", "顯示視線"},
        {"Offscreen Arrows", "螢幕外箭頭"},
        {"Arrow Color", "箭頭顏色"},
        {"Arrow Size", "箭頭大小"},
        {"Arrow Radius", "箭頭半徑"},
        {"Bloom Speed", "脈衝速度"},
        {"Minimum Glow", "最小發光"},
        {"Maximum Glow", "最大發光"},
        {"Threat Hitboxes", "威脅命中框"},

        // Sound ESP
        {"SOUND ESP", "聲音透視"},
        {"Sound ESP", "聲音透視"},
        {"Enable Sound ESP", "啟用聲音透視"},
        {"Ring Color", "圓環顏色"},
        {"Local Sync", "本地同步"},
        {"Duration", "持續時間"},
        {"Ring Radius", "圓環半徑"},
        {"Audible Distance", "可聽距離"},
        {"Head Hitbox Color", "頭部命中框顏色"},
        {"Body Hitbox Color", "身體命中框顏色"},
        {"Fill Alpha", "填充透明度"},

        // Chams materials
        {"Material", "材質"},
        {"Color", "顏色"},
        {"Wireframe", "線框"},
        {"Roughness", "粗糙度"},
        {"Metalness", "金屬度"},
        {"Exponent", "指數"},
        {"Falloff", "衰減"},
        {"Fresnel Filling", "菲涅爾填充"},
        {"Strength", "強度"},
        {"Speed", "速度"},
        {"Tint", "色調"},
        {"Solid", "實心"},
        {"Shaded", "著色"},
        {"Glow", "發光"},
        {"Glow Outline", "發光描邊"},
        {"Iridescent", "彩虹"},
        {"Water Flow", "水流"},
        {"Glossy", "光澤"},

        // Item ESP
        {"SETTINGS", "設定"},
        {"FILTERS", "過濾"},
        {"Enable Item ESP", "啟用物品透視"},
        {"Max Distance", "最大距離"},
        {"Show Icon", "顯示圖示"},
        {"Show Item Name", "顯示物品名稱"},
        {"Rifles", "步槍"},
        {"SMGs", "衝鋒槍"},
        {"Snipers", "狙擊槍"},
        {"Pistols", "手槍"},
        {"Grenades", "手雷"},
        {"Utility", "道具"},

        // Projectile ESP
        {"VISUAL ELEMENTS", "視覺元素"},
        {"COLORS", "顏色"},
        {"Enable Projectiles", "啟用投擲物"},
        {"Display Mode", "顯示模式"},
        {"Indicator", "指示器"},
        {"Text Only", "僅文字"},
        {"Show Text", "顯示文字"},
        {"Effect Timer", "效果計時器"},
        {"Effect Timer Ring", "效果計時環"},
        {"Inferno Bounds", "燃燒範圍"},
        {"INDICATOR", "指示器"},
        {"Timer Full", "計時滿"},
        {"Timer Low", "計時低"},
        {"Indicator Background", "指示器背景"},
        {"INFERNO GRADIENT", "燃燒漸層"},
        {"Gradient Width", "漸層寬度"},
        {"Gradient Opacity", "漸層不透明度"},
        {"HE Grenade", "高爆手雷"},
        {"Flashbang", "閃光彈"},
        {"Smoke", "煙霧彈"},
        {"Molotov", "燃燒彈"},
        {"Decoy", "誘餌彈"},

        // Bomb ESP
        {"STATES", "狀態"},
        {"SAFE ZONE (BAKED)", "安全區 (預先計算)"},
        {"Enable Bomb ESP", "啟用炸彈透視"},
        {"Show Carrier", "顯示攜帶者"},
        {"Show Planted", "顯示已安放"},
        {"Planted Color", "已安放顏色"},
        {"Defusing Color", "拆彈顏色"},
        {"Panel Background", "面板背景"},
        {"World Timer Ring", "世界計時環"},
        {"World Timer", "世界計時器"},
        {"Bomb Info Panel", "炸彈資訊面板"},
        {"Timer Color", "計時器顏色"},
        {"Safe Zone Contour", "安全區輪廓"},
        {"Zone Color", "區域顏色"},
        {"Gradient Bands", "漸層條帶"},
        {"Band Step", "條帶間距"},

        // Radar / world
        {"RADAR OVERLAY", "雷達覆蓋"},
        {"NO FLASH (WIREFRAME)", "無閃光 (線框)"},
        {"Enable Visual No Flash", "啟用視覺無閃光"},
        {"Render Distance", "渲染距離"},
        {"Dimming Overlay Color", "變暗覆蓋顏色"},
        {"Wireframe Color", "線框顏色"},
        {"NO SMOKE (WIREFRAME)", "無煙霧 (線框)"},
        {"Enable Visual No Smoke", "啟用視覺無煙霧"},
        {"Smoke Wireframe Color", "煙霧線框顏色"},

        // Crosshair
        {"CROSSHAIR SETTINGS", "準星設定"},
        {"Enable Crosshair", "啟用準星"},
        {"Draw Dot", "繪製點"},
        {"Draw Lines", "繪製線"},
        {"T-Style", "T 形"},
        {"Length", "長度"},
        {"Gap", "間隙"},
        {"Thickness", "粗細"},
        {"Draw Outline", "繪製描邊"},
        {"Primary Color", "主顏色"},
        {"Penetration Indicator", "穿透指示"},
        {"Can Penetrate", "可穿透"},
        {"Cannot Penetrate", "不可穿透"},

        // Misc tabs
        {"General", "一般"},
        {"Movement", "移動"},
        {"Effects", "效果"},
        {"Overlay", "覆蓋"},
        {"Lua API", "Lua API"},
        {"Configs", "設定"},

        // Misc - Lua
        {"LUA RUNTIME", "Lua 執行環境"},
        {"SCRIPTS", "指令碼"},
        {"Enable Lua API", "啟用 Lua API"},
        {"Script Directory", "指令碼目錄"},
        {"Open Folder", "開啟資料夾"},
        {"Load Lua Script", "載入 Lua 指令碼"},
        {"Copy link", "複製連結"},
        {"Copy Path", "複製路徑"},
        {"Discover Scripts", "探索指令碼"},
        {"Refresh", "重新整理"},
        {"No Lua scripts found", "找不到 Lua 指令碼"},
        {"Copy scripts into the Lua directory", "將指令碼放入 Lua 目錄"},
        {"Autoload", "自動載入"},
        {"Hot Reload", "熱重載"},
        {"Status", "狀態"},
        {"Runtime", "執行環境"},
        {"Last Error", "最後錯誤"},
        {"Reload Script", "重新載入指令碼"},
        {"Reload", "重新載入"},

        // Misc - General
        {"AUTOMATION", "自動化"},
        {"Auto Accept Match", "自動接受對局"},
        {"GRENADES", "手雷"},
        {"LINEUP HELPER", "站位助手"},
        {"GRENADE ASSIST", "手雷輔助"},
        {"TRAJECTORY", "軌跡"},
        {"Lineup Helper", "站位助手"},
        {"Draw Distance", "繪製距離"},
        {"Marker Distance", "標記距離"},
        {"Stand Radius", "站立半徑"},
        {"Release Radius", "釋放半徑"},
        {"Height Tolerance", "高度容差"},
        {"Show Throw Type", "顯示投擲類型"},
        {"Show Distance", "顯示距離"},
        {"Plaque Background", "標牌背景"},
        {"Plaque Text", "標牌文字"},
        {"Plaque Accent", "標牌強調色"},
        {"Stand Marker", "站立標記"},
        {"Stand Marker Active", "站立標記啟用"},
        {"Aim Marker", "瞄準標記"},
        {"Lineup Aim Assist", "站位瞄準輔助"},
        {"Aim Key", "瞄準鍵"},
        {"Auto Release", "自動釋放"},
        {"Lock Threshold", "鎖定閾值"},
        {"Settle Time", "穩定時間"},
        {"Enemy Aim Assist", "敵人瞄準輔助"},
        {"Activation Key", "啟用鍵"},
        {"Target FOV", "目標視野"},
        {"Trajectory Preview", "軌跡預覽"},
        {"Local Prediction Only", "僅本地預判"},
        {"Line Style", "線條樣式"},
        {"Line Color", "線條顏色"},
        {"Bloom", "脈衝"},
        {"Bloom Color", "脈衝顏色"},
        {"Bloom Radius", "脈衝半徑"},
        {"Bounce Points", "彈跳點"},
        {"End Point", "終點"},
        {"Point Color", "點顏色"},
        {"Point Size", "點大小"},

        // Misc - Engine / Interface
        {"ENGINE", "引擎"},
        {"FPS Limiter", "FPS 限制"},
        {"GPU Effects", "GPU 特效"},
        {"Restart to change GPU effects. The base overlay uses the display adapter; off keeps 2D ESP and the menu, while chams, no flash, no smoke and bloom are disabled.", "變更 GPU 特效後需重新啟動。基礎覆蓋層使用顯示適配器；關閉後仍保留 2D 透視和選單，但模型透視、無閃光、無煙霧和脈衝將被停用。"},
        {"Maximum FPS", "最大 FPS"},
        {"INTERFACE", "介面"},
        {"LANGUAGE", "語言"},
        {"Language", "語言"},
        {"DPI Scale", "DPI 縮放"},

        // Misc - Movement
        {"BUNNY HOP", "連跳"},
        {"EDGE JUMP", "邊緣跳"},
        {"Enable Bunny Hop", "啟用連跳"},
        {"Enable Edge Jump", "啟用邊緣跳"},
        {"GAME KEY BINDS", "遊戲按鍵綁定"},
        {"GAME ATTACK BINDS", "遊戲攻擊綁定"},
        {"Back", "後退"},
        {"Left", "左"},
        {"Right", "右"},
        {"Duck", "下蹲"},
        {"Attack", "攻擊"},
        {"Secondary Attack", "副攻擊"},
        {"Reset Game Binds", "重設遊戲綁定"},
        {"Reset", "重設"},
        {"Match these binds in the game; no automatic detection.", "請在遊戲中手動設定這些按鍵；本工具不會自動偵測。"},

        // Misc - Effects
        {"BULLET TRACERS", "子彈軌跡"},
        {"Enable Bullet Tracers", "啟用子彈軌跡"},
        {"Tracer Color", "軌跡顏色"},
        {"Fade Duration", "淡出持續時間"},
        {"Max Tracers", "最大軌跡數"},
        {"Bloom Effect", "脈衝效果"},
        {"Draw Impact Cubes", "繪製命中方塊"},
        {"Draw Trajectory Line", "繪製彈道線"},
        {"Cube Size", "方塊大小"},
        {"Fade Near", "近端淡出"},
        {"Fade Far", "遠端淡出"},

        // Misc - Overlay
        {"CAPTURE", "擷取"},
        {"OBS Bypass", "OBS 繞過"},
        {"WATERMARK", "浮水印"},
        {"Show Watermark", "顯示浮水印"},
        {"Show Ping", "顯示延遲"},
        {"Show Loss", "顯示封包遺失"},
        {"Show CPU Load", "顯示 CPU 使用率"},
        {"Show FPS", "顯示 FPS"},
        {"SPECTATOR LIST", "觀戰者列表"},
        {"Show Spectators", "顯示觀戰者"},
        {"EVENT LOG", "事件記錄"},
        {"Event Log", "事件記錄"},
        {"Show Event Log", "顯示事件記錄"},
        {"Maximum Entries", "最大項目"},
        {"Events", "事件"},
        {"Shots", "射擊"},
        {"Hits", "命中"},
        {"Kills", "擊殺"},
        {"Misses", "未命中"},
        {"Blocked", "被阻擋"},
        {"Info", "資訊"},
        {"ACTIVE BINDS", "作用中綁定"},
        {"Active Binds", "作用中綁定"},
        {"Show Active Binds", "顯示作用中綁定"},
        {"Always On Binds", "始終開啟綁定"},
        {"Hold Binds", "按住綁定"},
        {"Toggle Binds", "切換綁定"},
        {"BOMB PANEL", "炸彈面板"},
        {"Show Bomb Info", "顯示炸彈資訊"},
        {"No active entries", "無作用中項目"},
        {"Spectators", "觀戰者"},
        {"Steam Avatars", "Steam 頭像"},
        {"  fixed camera", "  固定視角"},
        {"  first person", "  第一人稱"},
        {"  third person", "  第三人稱"},
        {"  free camera", "  自由視角"},

        // Misc - Configs
        {"CFG FILE", "設定檔"},
        {"File Name", "檔案名稱"},
        {"Export Named CFG", "匯出命名設定"},
        {"Save As...", "另存新檔..."},
        {"Open CFG", "開啟設定"},
        {"Browse...", "瀏覽..."},

        // ESP editor
        {"ESP EDITOR", "ESP 編輯器"},
        {"PREVIEW UNAVAILABLE", "預覽無法使用"},

        // Nade helper action tokens
        {"Manual lineup", "手動站位"},
        {"Hold {}, release", "按住 {}, 放開"},
        {"Hold {}, {}, release", "按住 {}, {}, 放開"},
        {"LMB", "左鍵"},
        {"RMB", "右鍵"},
        {"LMB+RMB", "左鍵+右鍵"},
        {"m", "公尺"},
        {"Jump+Throw", "跳躍+投擲"},
        {"W+Jump+Throw", "W+跳躍+投擲"},
        {"Run+Jump+Throw", "跑動+跳躍+投擲"},
        {"Walk+Jump+Throw", "走動+跳躍+投擲"},
        {"Crouch+Jump+Throw", "下蹲+跳躍+投擲"},
        {"Crouch+W+Jump+Throw", "下蹲+W+跳躍+投擲"},
        {"Crouch+Run+Jump+Throw", "下蹲+跑動+跳躍+投擲"},
        {"WJump+Throw", "W跳躍+投擲"},
        {"Jump+Throw LRMB", "跳躍+投擲 左右鍵"},
        {"Jump+Throw RMB", "跳躍+投擲 右鍵"},
        {"W+Jump+Throw LRMB", "W+跳躍+投擲 左右鍵"},
        {"W+Jump+Throw RMB", "W+跳躍+投擲 右鍵"},
        {"Run+Jump+Trhow", "跑動+跳躍+投擲"},
        {"W+Jump+Throwv", "W+跳躍+投擲"},
        {"Throw", "投擲"},
        {"Throw LRMB", "投擲 左右鍵"},
        {"Throw RMB", "投擲 右鍵"},
        {"Throw (crouch)", "投擲 (下蹲)"},
        {"Throw (break glass)", "投擲 (破窗)"},
        {"Run+Thorw", "跑動+投擲"},
        {"Run+Throw", "跑動+投擲"},
        {"Crouch+Run+Throw", "下蹲+跑動+投擲"},
        {"Go Left then W+Jump+Throw", "先左移再 W+跳躍+投擲"},
        {"Go Right then W+Jump+Throw", "先右移再 W+跳躍+投擲"},
        {"Complex, move left and back and jumpthrow while running", "複雜：向左後移動並在跑動中跳躍投擲"},
        {"Insta Window (no autothrow)", "快速視窗 (不自動投擲)"},
        {"Insta Long Door (no autothrow)", "快速長門 (不自動投擲)"},

        // Fallback tokens
        {"Crouch", "下蹲"},
        {"Run", "跑動"},
        {"Walk", "走動"},
        {"Step", "步伐"},
        {"Forward", "前進"},
        {"Trhow", "投擲"},
        {"Thorw", "投擲"},
        {"Throwv", "投擲"},
    };

    return table;
}

const std::unordered_map<std::string_view, const char *> &table_for(id value)
{
    return value == id::zh_hant ? traditional() : value == id::zh ? chinese() : russian();
}

} // namespace

void set(id value)
{
    if (value >= id::en && value < id::count)
    {
        g_current.store(value, std::memory_order_relaxed);
    }
}

id current()
{
    return g_current.load(std::memory_order_relaxed);
}

const char *code(id value)
{
    return value == id::ru ? "RU"
        : value == id::zh ? "ZH"
        : value == id::zh_hant ? "TW"
        : "EN";
}

const char *tr(const char *english)
{
    if (!english || current() == id::en)
    {
        return english;
    }

    const auto &table = table_for(current());
    const auto it = table.find(std::string_view{english});
    return it == table.end() ? english : it->second;
}

std::string_view tr(std::string_view english)
{
    if (current() == id::en)
    {
        return english;
    }

    const auto &table = table_for(current());
    const auto it = table.find(english);
    return it == table.end() ? english : std::string_view{it->second};
}

const char *cjk_glyph_text()
{
    static const std::string text = []
    {
        std::string out;
        const auto append = [ &out ]( const std::unordered_map<std::string_view, const char *> &table )
        {
            for ( const auto &entry : table )
            {
                out.append( entry.second );
            }
        };
        append( chinese() );
        append( traditional() );
        out.append( "简体中文繁體中文" );
        return out;
    }( );

    return text.c_str( );
}

} // namespace render::localization
